import re


def remove_keywords(text):
    keywords = [rf'\b{re.escape(kw)}\b' for kw in [
        "EPOCH\s\d{1,2}:\s?(\d{4}|\d{1,2}/\d{1,2})\s\d{1,2}:\d{1,2}\s?to\s?(\d{2,4}|\d{1,2}/\d{1,2})\s\d{1,2}:\d{1,2}",
        "Brigham and Women’?s",
        "Brigham And Women'?s/Mass(achusetts)? General Health Care Center",
        "Brigham and Women\\s Hospital",
        "Brigham & Women's Hospital",
        "Brigham and Women's Hospital",
        "Brigham and Women's Hosptial",
        "Brigham and Womens",
        "Brigham and Womens Hospital",
        "Brigham and Women's Hosptial",
        "Brigham and Women's Faulkner Hospital",
        "Brigham And Womens Primary Care",
        "Mass(achusetts)? General Hospital",
        "Massachusetts General Hospital",
        "Lawrence General Hospital",
        "Massachusetts General",
        "Mass General Brigham",
        "Boston",
        "South Shore Health Systems",
        "South Shore Health",
        "South Shore Hospital",
        "A Teaching Affiliate of Harvard Medical School",
        "Harvard Medical School",
        "Partners Neurology Resident",
        "Partners Compliance",
        "MGH",
        "BWH",
        "MGB",
        "\d{1,2}\s?(jan|feb|mar|apr|may|june|jun|july|jul|aug|sept|sep|oct|nov|dec)\.?\s+?\d{2,4}",
        "\d{1,2}\s?(Jan|Feb|Mar|Apr|May|June|Jun|July|Jul|Aug|Sept|Sep|Oct|Nov|Dec)\.?\s+?\d{2,4}",
        "\d{1,2}\s?(january|february|march|april|may|june|july|august|september|october|november|december)\s+?\d{2,4}",
        "\d{1,2}\s?(January|February|March|April|May|June|July|August|September|October|November|December)\s+?\d{2,4}",
        "medical school",
        "SALEM HOSPITAL",
        "Newton-Wellesley Hospital",
        "Newton Wellesley Hospital",
        "NWH",
        "Union Hospital",
        "McLean Hospital",
        "Cooley Dickinson Hospital",
        "Cooley Dickinson",
        "North Shore Medical Center",
        "Partners Healthcare",
        "Milford Regional Medical Ctr",
        "MILFORD REGIONAL MEDICAL CENTER",
        "BWF",
        "NCH",
        "Nantucket Cottage Hospital",
        "NSMC",
        "DFCI",
        "Dana-Farber Cancer Institute",
        "Dana Farber Cancer Institute",
        "Dana Farber Cancer Institiute",
        "Harbor Medical Associates",
        "HMA",
        "Wentworth-Douglass Hospital",
        "WDH",
        "Spaulding Rehabilitation Hospital",
        "SRH",
        "Mass Eye and Ear",
        "MASSACHUSETTS EYE & EAR",
        "MASSACHUSETTS EYE AND EAR INFIRMARY",
        "MEE",
        "MEEI",
        "Martha's Vineyard Hospital",
        "MVH",
        "Spaulding Hospital",
        "SCC",
        "SHAUGHNESSY-KAPLAN REHABILITATION HOSPITAL",
        "F A U L K N E R   H O S P I T A L",
        "FAULKNER HOSPITAL",
        "Brigham and Women's Faulkner Hospital",
        "BRIGHAM INTERNAL MEDICINE ASSOCIATES",
        "BRIGHAM INTERNAL MEDICINE",
        "BRIGHAM AND WOMEN'S PHYSICIAN GROUP",
        "ROBERT B. BRIGHAM ARTHRITIS CENTER",
        "BRIGHAM MEDICAL GROUP",
        "BRIGHAM ORTHOPEDIC ASSOCIATES",
        "BRIGHAM EMERGENCY DEPT VISIT",
        "GENERAL MEDICAL ASSOCIATES",
        "WOMEN'S HEALTH CENTER",
        "NORWOOD HEALTHCARE ASSOCIATES",
        "SOUTHERN JAMAICA PLAIN HEALTH CENTER",
        "Union Hospital",
        "Sandra",
        "Samartian",
        "Renagel",
        "Orlando",
        "obrien",
        "NYU",
        "Mooremary",
        "Mayo",
        "kuwaiti",
        "fra ncisco",
        "Francisco",
        "Framingham",
        "Fogarty",
        "Crawford",
        "North Shore Physicians Group",
        "BIDMC",
        "Affiliation: BIDMC",
        "BIDHC",
        "Lahey Danvers",
        "BI",
        "BID#",
        "BID#:",
        "BID #",
        "BID #:",
        "BIH#",
        "BIH#:",
        "BIH #:",
        "BMC",
        "Lahey",
        "BETH ISAREL",
        "Beth Israel Deaconess Medical Center",
        "Beth Isarel Deaconess Healthcare - Washington Square Group",
        "Beth-Israel Deaconess HealthCare-Lexington",
        "Beth-Israel Deaconess",
        "deaconess healthcare",
        "BETH ISAREL LAHEY HEALTH",
        "Beth Israel Deaconess Medical Center/East",
        "330 Brookline Avenue, E/CC-6",
        "330 Brookline Ave",
        "East Campus",
        "3rd floor Shapiro",
        "MR#",
        "mr#",
        "MRN",
        "SHAPIRO CLINICAL CENTER",
        "UMASS BOSTON",
        "Puya",
        "Yvo"
    ]]

    for keyword in keywords:
        # Adjusted regex pattern to remove hospital names with flexibility for spaces and line breaks
        pattern = re.compile(keyword, flags=re.IGNORECASE | re.DOTALL)
        text = re.sub(pattern, '*****', text)

    return text


# Example usage:
'''
paragraph = ""
result = remove_keywords(paragraph)
print("Deidentified Result:\n", result)
'''
