import re


def remove_keywords(text):
    keywords = [rf'\b{re.escape(kw)}\b' for kw in [
        "EPOCH\s\d{1,2}:\s?(\d{4}|\d{1,2}/\d{1,2})\s\d{1,2}:\d{1,2}\s?to\s?(\d{2,4}|\d{1,2}/\d{1,2})\s\d{1,2}:\d{1,2}",
        "Brigham and Women’?s",
        "Brigham And Women'?s/Mass(achusetts)? General Health Care Center",
        "Brigham and Women\\s Hospital",
        "Brigham & Women's Hospital",
        "Brigham and Women's Hospital",
        "Brigham and Women's Hosptial",
        "Brigham and Womens",
        "Brigham and Womens Hospital",
        "Brigham and Women's Hosptial",
        "Brigham and Women's Faulkner Hospital",
        "Brigham And Womens Primary Care",
        "Mass(achusetts)? General Hospital",
        "Massachusetts General Hospital",
        "Lawrence General Hospital",
        "Massachusetts General",
        "Mass General Brigham",
        "South Shore Health Systems",
        "South Shore Health",
        "South Shore Hospital",
        "A Teaching Affiliate of Harvard Medical School",
        "Harvard Medical School",
        "HMS",
        "Partners Neurology Resident",
        "Partners Compliance",
        "MGH",
        "BWH",
        "MGB",
        "\d{1,2}\s?(jan|feb|mar|apr|may|june|jun|july|jul|aug|sept|sep|oct|nov|dec)\.?\s+?\d{2,4}",
        "\d{1,2}\s?(Jan|Feb|Mar|Apr|May|June|Jun|July|Jul|Aug|Sept|Sep|Oct|Nov|Dec)\.?\s+?\d{2,4}",
        "\d{1,2}\s?(january|february|march|april|may|june|july|august|september|october|november|december)\s+?\d{2,4}",
        "\d{1,2}\s?(January|February|March|April|May|June|July|August|September|October|November|December)\s+?\d{2,4}",
        "medical school",
        "SALEM HOSPITAL",
        "Newton-Wellesley Hospital",
        "Newton Wellesley Hospital",
        "NWH",
        "Union Hospital",
        "McLean Hospital",
        "Cooley Dickinson Hospital",
        "Cooley Dickinson",
        "North Shore Medical Center",
        "Wentworth Douglas Hospital",
        "Partners Healthcare",
        "Milford Regional Medical Ctr",
        "MILFORD REGIONAL MEDICAL CENTER",
        "BWF",
        "NCH",
        "Nantucket Cottage Hospital",
        "NSMC",
        "DFCI",
        "Dana-Farber Cancer Institute",
        "Dana Farber Cancer Institute",
        "Dana Farber Cancer Institiute",
        "Harbor Medical Associates",
        "HMA",
        "Wentworth-Douglass Hospital",
        "WDH",
        "Spaulding Rehabilitation Hospital",
        "SRH",
        "Mass Eye and Ear",
        "MASSACHUSETTS EYE & EAR",
        "MASSACHUSETTS EYE AND EAR",
        "MASSACHUSETTS EYE AND EAR INFIRMARY",
        "MEE",
        "MEEI",
        "Martha's Vineyard Hospital",
        "MVH",
        "Spaulding Hospital",
        "SCC",
        "SHAUGHNESSY-KAPLAN REHABILITATION HOSPITAL",
        "F A U L K N E R   H O S P I T A L",
        "FAULKNER HOSPITAL",
        "Brigham and Women's Faulkner Hospital",
        "BRIGHAM INTERNAL MEDICINE ASSOCIATES",
        "BRIGHAM INTERNAL MEDICINE",
        "BRIGHAM AND WOMEN'S PHYSICIAN GROUP",
        "ROBERT B. BRIGHAM ARTHRITIS CENTER",
        "BRIGHAM MEDICAL GROUP",
        "BRIGHAM ORTHOPEDIC ASSOCIATES",
        "BRIGHAM EMERGENCY DEPT VISIT",
        "GENERAL MEDICAL ASSOCIATES",
        "WOMEN'S HEALTH CENTER",
        "NORWOOD HEALTHCARE ASSOCIATES",
        "SOUTHERN JAMAICA PLAIN HEALTH CENTER",
        "Union Hospital",
        "Beverly Hospital",
        "Addison Gilbert Hospital",
        "TUFTS MEDICAL CENTER",
        "St Luke's Hospital",
        "MaineHealth's",
        "Sandra",
        "Samartian",
        "Renagel",
        "Orlando",
        "obrien",
        "NYU",
        "Mooremary",
        "Mayo",
        "kuwaiti",
        "fra ncisco",
        "Francisco",
        "Framingham",
        "Fogarty",
        "Crawford",
        "North Shore Physicians Group",
        "BIDMC",
        "Affiliation: BIDMC",
        "Bidmc-Medicine",
        "BIDHC",
        "Bilhpc",
        "Lahey Danvers",
        "BI",
        "BID#",
        "BID#:",
        "BID #",
        "BID #:",
        "BIH#",
        "BIH#:",
        "BIH #:",
        "BMC",
        "Lahey",
        "BETH ISAREL",
        "Beth Israel Deaconess Medical Center",
        "Beth Isarel Deaconess Healthcare - Washington Square Group",
        "Beth-Israel Deaconess HealthCare-Lexington",
        "Beth-Israel Deaconess",
        "deaconess healthcare",
        "Lahey Health",
        "Lahey Outpatient Center Danvers",
        "BETH ISAREL LAHEY HEALTH",
        "Beth Israel Deaconess Medical Center/East",
        "Uphams Corner Health Center",
        "Hebrew Senior Life",
        "Nashua Eye Associates",
        "330 Brookline Avenue, E/CC-6",
        "330 Brookline Ave",
        "East Campus",
        "3rd floor Shapiro",
        "MR#",
        "MR#:",
        "mr#",
        "MRN",
        "SHAPIRO CLINICAL CENTER",
        "Joslin Diabetes Center",
        "Merrimack Valley Internal Medicine Associates",
        "UMASS BOSTON",
        "Puya",
        "Yvo",
        "Boston Children's Hospital",
        "Boston Childrens Hospital",
        "Boston Children’s Hospital",
        "Childrens Hospital",
        "Children's Hospital",
        "Children’s Hospital",
        "Children's",
        "Children’s",
        "Childrens Hospital",
        "Children’s Hospital",
        "children's hospital",
        "childrens hosp",
        "children's hosp",
        "children’s hosp",
        "CHILDREN'S HOSPITAL BOSTON",
        "BCH",
        ":BCH",
        "\bBCH\b",
        "General Instructions BCH",
        "CHB",
        "\bCHB\b",
        "300 Longwood Avenue",
        "300 Longwood Ave",
        "www.BostonChildrens.org",
        "www.childrenshospital.org",
        "www.mychildrens.org",
        "Boston Children's Hospital",
        "St. Elizabeth's",
        "St. Elizabeth's Medical Center",
        "Martha Eliot Health Center",
        "New England Pediatric Care Center",
        "New England Pediatric Care",
        "78 Boston Road",
        "NEPC",
        "CHILDREN'S HOSPITAL BOSTON",
        "Elliot Hospital",
        "Floating Hospital",
        "MyChildren's Portal",
        "MyChildrens",
        "South Shore Hospital",
        "Boston Childrens Physicians",
        "Cambridge Hospital",
        "Cambridge Health Alliance",
        "Boston Children's Waltham",
        "MassGeneral Hospital for Children",
        "Lowell General Hospital",
        "Johns Hopkins Hospital",
        "The Johns Hopkins Hospital",
        "Alameda Hospital",
        "UCSF",
        "University of California, San Francisco",
        "Stanford Hospital",
        "Stanford Hospital and Clinics",
        "Menlo Medical Clinic",
        "www.menloclinic.com",
        "Bayside Medical Group",
        "Stanford Children’s Health",
        "Stanford University",
        "Stanford Health Care",
        "Stanford Healthcare",
        "Stanford Healthcare TriValley",
        "Stanford University School of Medicine",
        "Diablo Valley Child Neurology",
        "Shield Healthcare",
        "https://gregor.stanford.edu/",
        "GREGoR",
        "https://evercore.stanfordmed.org/",
        "STANFORD MEDICINE",
        "http://prism.stanfordmedicine.org",
        "Stanford Pulmonary Lab",
        "Stanford University Medical Center",
        "Stanford Family Practice",
        "Stanford Hospital and Clinics",
        "UCSF Stanford Health Care",
        "STANFORD MEDICAL GROUP",
        "STANFORD MEDICAL CENTER",
        "LUCILE SALTER PACKARD",
        "LUCILE SALTER PACKARD CHILDREN'S HOSPITAL",
        "Stanford Hematology",
        "ACCESSION NUMBER:",
        "ACCESSION #:",
        "Accession#:",
        "Carol Ann Read Breast Health Center",
        "John Muir Health",
        "Stanford Center for Inherited Cardiovascular Disease",
        "Palo Alto Medical Foundation",
        "Stanford Sleep Medicine Center",
        "Subject Code:",
        "Hospital # :",
        "MEDICAL RECORD #:",
        "Packard's Children's Health Alliance",
        "Sutter Pacific Medical Center",
        "Stanford Pain Management Center",
        "Lucile Packard Children's Hospital",
        "Palo Alto Medical Clinic",
        "UNIVERSITY OF CALIFORNIA SAN FRANCISCO ",
        "El Camino Hospital",
        "Mount Sinai Medical Center",
        "Mayo Clinic",
        "Cleveland Clinic"
    ]]



    for keyword in keywords:
        # Adjusted regex pattern to remove hospital names with flexibility for spaces and line breaks
        pattern = re.compile(keyword, flags=re.IGNORECASE | re.DOTALL)
        text = re.sub(pattern, '*****', text)

    return text


# Example usage:
'''
paragraph = ""
result = remove_keywords(paragraph)
print("Deidentified Result:\n", result)
'''
